# Generated by Django 6.0.7 on 2026-07-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Marketplace', max_length=200)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('site_keywords', models.CharField(blank=True, max_length=225, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photos/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='photos/favicon/')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
