# Generated by Django 6.0.6 on 2026-07-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('admin', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
