# Generated by Django 6.0.6 on 2026-07-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='admin',
            new_name='author',
        ),
    ]
